name = "lean-datalog"
defaultTargets = ["extract"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.31.0"

[[lean_lib]]
name = "LeanDatalog"

[[lean_lib]]
name = "Examples"

[[lean_exe]]
name = "extract"
root = "Main"
