import LeanDatalog.Basic

/-!
# Driver: environment → relational facts

Given an already-elaborated `Environment` and a set of "target" modules
(the modules compiled in this run), we:

1. find every `theorem` whose declaration lives in a target module;
2. emit `decl(name, kind, typeRoot)` plus the encoded statement `Expr` for each;
3. transitively walk the constants those statements reference and emit a
   `decl` row + encoded *type* for each dependency, plus `depends_on` edges.

Only **types** (statements) are encoded — never proof terms — matching the
requirement that a statement of the proved fact is sufficient.
-/

namespace LeanDatalog

open Lean

/-- The constants referenced by an expression (statement). -/
def usedConsts (e : Expr) : Array Name :=
  e.getUsedConstants

/-- Build the set of module indices corresponding to the requested target modules. -/
def targetModuleIdxs (env : Environment) (targets : Array Name) : Std.HashSet Nat := Id.run do
  let targetSet : Std.HashSet Name := targets.foldl (·.insert ·) {}
  let mut idxs : Std.HashSet Nat := {}
  let names := env.header.moduleNames
  for h : i in [0:names.size] do
    if targetSet.contains names[i] then
      idxs := idxs.insert i
  return idxs

/-- Is constant `n` defined in one of the target modules? -/
def definedInTargets (env : Environment) (idxs : Std.HashSet Nat) (n : Name) : Bool :=
  match env.getModuleIdxFor? n with
  | some idx => idxs.contains idx.toNat
  | none     => false

/-- The name of the module that defines `n`, if any (none ⇒ defined in this file). -/
def moduleNameOf? (env : Environment) (n : Name) : Option Name :=
  match env.getModuleIdxFor? n with
  | some idx => env.header.moduleNames[idx.toNat]?
  | none     => none

/-- Does module name `m` fall under one of the dotted prefixes (`P` or `P.…`)? -/
def matchesPrefix (prefixes : List String) (m : Name) : Bool :=
  let s := m.toString
  prefixes.any fun p => s == p || (p ++ ".").isPrefixOf s

/-- True for `theorem` declarations. -/
def isTheorem : ConstantInfo → Bool
  | .thmInfo _ => true
  | _          => false

/-- Last components Lean appends to auto-generated lemmas (equation lemmas,
    structural eliminators, structure projections' specs, etc.). -/
def autoGenSuffixes : List String :=
  ["eq_def", "eq_unfold", "injEq", "inj", "sizeOf_spec", "noConfusion",
   "noConfusionType", "brecOn", "below", "ind", "rec", "recOn", "casesOn",
   "fwdDeriv", "ndrec"]

/-- Heuristic: is `n` an auto-generated declaration rather than one the user wrote?
    Catches compiler internals, equation lemmas (`foo.eq_1`, `foo.match_2.eq_3`),
    private proof terms (`foo._proof_5`), and structural lemmas. -/
def isAutoGenerated (n : Name) : Bool :=
  n.isInternalDetail || go n
where
  go : Name → Bool
    | .anonymous   => false
    | .num _ _     => true                      -- numeric components ⇒ generated
    | .str p s     =>
        autoGenSuffixes.contains s
        || s.startsWith "eq_" || s.startsWith "match_" || s.startsWith "_proof_"
        || s.startsWith "proof_" || s.startsWith "_eq_" || s.startsWith "_cstage"
        || go p

/-- Should this theorem be seeded as a "target" (vs. treated as noise)? -/
def isUserFacingTheorem (includeAll : Bool) (ci : ConstantInfo) (n : Name) : Bool :=
  isTheorem ci && (includeAll || !isAutoGenerated n)

/-- Extraction options. -/
structure Config where
  /-- Keep auto-generated theorems (`eq_1`, `injEq`, …) in the seed set. -/
  includeAll : Bool := false
  /-- Encode definition/opaque *bodies* (`decl_value` + `value_uses`). -/
  values : Bool := false
  /-- Encode theorem *proof terms* too (large; expands the closure). -/
  proofs : Bool := false
  /-- Seed theorems from every module whose name matches one of these prefixes
      (e.g. `["Mathlib"]`), instead of only the modules named on the command line.
      Empty ⇒ use the named-modules behaviour. -/
  modulePrefixes : List String := []
  /-- Reset the hash-cons tables before each declaration: bounds memory to one
      statement at a time (no cross-declaration subterm sharing). Needed for
      whole-Mathlib runs on a memory-constrained machine. -/
  noShare : Bool := false

/-- Is `n` a theorem we should seed, given the config (named-modules or prefix mode)? -/
def isSeedTheorem (env : Environment) (cfg : Config) (idxs : Std.HashSet Nat)
    (ci : ConstantInfo) (n : Name) : Bool :=
  isUserFacingTheorem cfg.includeAll ci n &&
    (if cfg.modulePrefixes.isEmpty then
        definedInTargets env idxs n
      else match moduleNameOf? env n with
        | some m => matchesPrefix cfg.modulePrefixes m
        | none   => false)

/-- The defining value of a constant, if any: definition/opaque body or proof term. -/
def constValue? : ConstantInfo → Option Expr
  | .defnInfo v   => some v.value
  | .opaqueInfo v => some v.value
  | .thmInfo v    => some v.value
  | _             => none

/-- Given the config, should we encode this constant's value? -/
def shouldEncodeValue (cfg : Config) : ConstantInfo → Bool
  | .defnInfo _   => cfg.values
  | .opaqueInfo _ => cfg.values
  | .thmInfo _    => cfg.proofs
  | _             => false

/-- Encode one constant: a `decl` row (kind + statement root) and `depends_on` edges,
    and — when enabled — its value as `decl_value` + `value_uses` edges.
    Returns every constant it references (type-level always; value-level when the
    value was encoded), so the worklist closes over them. -/
def encodeConst (cfg : Config) (ci : ConstantInfo) : EncM (Array Name) := do
  let name := ci.name
  let rootId ← encodeExpr ci.type
  emit "decl" #[nm name, constKind ci, toString rootId]
  let mut deps := usedConsts ci.type
  for d in deps do
    emit "depends_on" #[nm name, nm d]
  if shouldEncodeValue cfg ci then
    if let some val := constValue? ci then
      let vRoot ← encodeExpr val
      emit "decl_value" #[nm name, toString vRoot]
      let vdeps := usedConsts val
      for d in vdeps do
        emit "value_uses" #[nm name, nm d]
      deps := deps ++ vdeps
  return deps

/-- Every relation we emit. Pre-creating empty `.facts` files for all of them means
    Soufflé's `.input` directives always find a file, even for unused node kinds. -/
def allRelations : List String :=
  ["decl", "target_theorem", "depends_on", "decl_value", "value_uses",
   "expr_node", "expr_bvar", "expr_fvar", "expr_mvar", "expr_sort",
   "expr_const", "expr_const_level", "expr_app", "expr_lam", "expr_forall",
   "expr_let", "expr_lit_nat", "expr_lit_str", "expr_mdata", "expr_proj",
   "level_node", "level_succ", "level_max", "level_imax", "level_param"]

/-- Main extraction over an environment, restricted to `targets` (+ their dep closure). -/
def extract (env : Environment) (targets : Array Name) (dir : System.FilePath)
    (cfg : Config := {}) : IO Unit := do
  IO.FS.createDirAll dir
  -- Pre-create all fact files (empty) so Soufflé always finds its inputs.
  for rel in allRelations do
    IO.FS.writeFile (dir / s!"{rel}.facts") ""
  let idxs := targetModuleIdxs env targets
  let run : EncM Nat := do
    -- Seed: every theorem matching the config (named modules, or module prefixes).
    let mut worklist : Array Name := #[]
    let mut seen : Std.HashSet Name := {}
    for (name, ci) in env.constants.toList do
      if isSeedTheorem env cfg idxs ci name then
        emit "target_theorem" #[nm name]
        worklist := worklist.push name
        seen := seen.insert name
    IO.eprintln s!"seeded {worklist.size} theorems; encoding statements…"
    -- Transitively encode statements (and, when enabled, values) of everything reachable.
    let mut processed := 0
    while !worklist.isEmpty do
      let name := worklist.back!
      worklist := worklist.pop
      match env.find? name with
      | none => pure ()
      | some ci =>
        -- Bound memory: forget cross-declaration subterm sharing if requested.
        if cfg.noShare then
          modify fun s => { s with exprIds := {}, levelIds := {} }
        let deps ← encodeConst cfg ci
        for d in deps do
          if !seen.contains d then
            seen := seen.insert d
            worklist := worklist.push d
        processed := processed + 1
        if processed % 20000 == 0 then
          IO.eprintln s!"  … {processed} declarations encoded ({(← get).nextId} nodes)"
    return processed
  let (processed, st) ← run.run { dir }
  -- Flush and close all handles.
  for (_, h) in st.handles.toList do
    h.flush
  let sharing := if cfg.noShare then "no cross-decl sharing"
                 else s!"{st.exprIds.size} distinct exprs"
  IO.println s!"encoded {processed} declarations, {st.nextId} total nodes ({sharing}) into {dir}"

end LeanDatalog
